#!/usr/bin/env bash
# Define the server address (replace with your actual server address)
SERVER_ADDRESS="34.203.201.154"

# Use ssh with single-character flags to connect to the server
ssh -i ~/.ssh/school ubuntu@$SERVER_ADDRESS
